Repository apcountryman/picolibrary-microchip-megaavr, pull requests merged in 2021-02, with the labels that each got.

#83 Remove ::picolibrary::Microchip namespace definition and associated header/source files
  include/picolibrary/microchip.h
  source/CMakeLists.txt
  source/picolibrary/microchip.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#93 Enable compiler C++ extensions
  CMakeLists.txt
Labels: priority-normal, status-awaiting_approval, type-refactoring

#94 Add SPI peripheral
  include/picolibrary/microchip/megaavr/peripheral/atmega2560.h
  include/picolibrary/microchip/megaavr/peripheral/atmega328p.h
  include/picolibrary/microchip/megaavr/peripheral/spi.h
  source/CMakeLists.txt
  source/picolibrary/microchip/megaavr/peripheral/spi.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#109 Remove doxygen generated documentation
  CMakeLists.txt
  documentation/Doxyfile.in
  documentation/mainpage.md
  include/picolibrary/microchip/megaavr/asynchronous_serial.h
  include/picolibrary/microchip/megaavr/gpio.h
  include/picolibrary/microchip/megaavr/peripheral/instance.h
  include/picolibrary/microchip/megaavr/peripheral/port.h
  include/picolibrary/microchip/megaavr/peripheral/spi.h
  include/picolibrary/microchip/megaavr/peripheral/usart.h
  include/picolibrary/microchip/megaavr/register.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#110 Update clang-format configuration
  .clang-format
  include/picolibrary/microchip/megaavr/asynchronous_serial.h
  include/picolibrary/microchip/megaavr/gpio.h
Labels: priority-normal, status-awaiting_approval, type-enhancement

#111 Add CI format job
  .github/workflows/ci.yml
  ci/format
Labels: priority-normal, status-awaiting_approval, type-enhancement

#112 Consolidate compiler flags
  CMakeLists.txt
  configuration/CMakeLists.txt.analysis
  configuration/CMakeLists.txt.release-atmega2560
  configuration/CMakeLists.txt.release-atmega328p
  configuration/CMakeLists.txt.testing-interactive-atmega2560-arduino-mega-2560
  configuration/CMakeLists.txt.testing-interactive-atmega328p-adafruit-metro-mini
  configuration/CMakeLists.txt.testing-interactive-atmega328p-arduino-uno
Labels: priority-normal, status-awaiting_approval, type-refactoring

#118 Add SPI facilities namespace
  include/picolibrary/microchip/megaavr/spi.h
  source/CMakeLists.txt
  source/picolibrary/microchip/megaavr/spi.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#119 Add SPI basic controller
  include/picolibrary/microchip/megaavr/spi.h
Labels: priority-normal, status-awaiting_approval, type-feature

#120 Add SPI controller
  include/picolibrary/microchip/megaavr/spi.h
Labels: priority-normal, status-awaiting_approval, type-feature

#122 Fix link time optimization
  CMakeLists.txt
Labels: priority-normal, status-awaiting_approval, type-bug

#129 Update SPI controller configuration documentation to match picolibrary
  include/picolibrary/microchip/megaavr/spi.h
Labels: priority-normal, status-awaiting_approval, type-refactoring

#130 Add explicit infinite loops to interactive test programs
  test/interactive/picolibrary/asynchronous_serial/unbuffered_output_stream/hello_world/microchip/megaavr/main.cc
  test/interactive/picolibrary/microchip/megaavr/asynchronous_serial/transmitter_8_n_1/hello_world/main.cc
  test/interactive/picolibrary/microchip/megaavr/gpio/open_drain_io_pin/toggle/main.cc
  test/interactive/picolibrary/microchip/megaavr/gpio/push_pull_io_pin/toggle/main.cc
  test/interactive/picolibrary/microchip/megaavr/spi/controller/spi/echo/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#131 Fix USART register field bit mask types
  include/picolibrary/microchip/megaavr/peripheral/usart.h
Labels: priority-normal, status-awaiting_approval, type-bug

#135 Fix SPI peripheral based SPI basic controller construction/initialization
  include/picolibrary/microchip/megaavr/spi.h
Labels: priority-normal, status-awaiting_approval, type-bug

#137 Remove unnecessary device select pin manipulation
  configuration/CMakeLists.txt.testing-interactive-atmega2560-arduino-mega-2560
  configuration/CMakeLists.txt.testing-interactive-atmega328p-adafruit-metro-mini
  configuration/CMakeLists.txt.testing-interactive-atmega328p-arduino-uno
  test/interactive/picolibrary/microchip/megaavr/spi/controller/spi/echo/CMakeLists.txt
  test/interactive/picolibrary/microchip/megaavr/spi/controller/spi/echo/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#143 Update author list
  README.md
Labels: priority-normal, status-awaiting_approval, type-enhancement

#142 Add TWI peripheral
  include/picolibrary/microchip/megaavr/peripheral/atmega2560.h
  include/picolibrary/microchip/megaavr/peripheral/atmega328p.h
  include/picolibrary/microchip/megaavr/peripheral/twi.h
  source/CMakeLists.txt
  source/picolibrary/microchip/megaavr/peripheral/twi.cc
Labels: priority-normal, status-awaiting_approval, type-feature

#145 Use designated initializers when initializing structs
  test/interactive/picolibrary/microchip/megaavr/spi/controller/spi/echo/main.cc
  test/interactive/picolibrary/microchip/megaavr/spi/controller/usart/echo/main.cc
Labels: priority-normal, status-awaiting_approval, type-refactoring

#148 Add I2C facilities namespace
  include/picolibrary/microchip/megaavr/i2c.h
  source/CMakeLists.txt
  source/picolibrary/microchip/megaavr/i2c.cc
Labels: priority-normal, status-awaiting_approval, type-feature
